
export const SET_LOGIN_USER_DATA = "SET_LOGIN_USER_DATA";


export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILURET = "USER_REGISTRATION_FAILURET";


export const SET_MAIN_PAGE = "SET_MAIN_PAGE";

export const PAGE_LOGIN = "PAGE_LOGIN";
export const PAGE_ABOUT = "PAGE_ABOUT";
export const PAGE_USER_REGISTRATION = "PAGE_USER_REGISTRATION";
export const PAGE_DASHBOARD = "PAGE_DASHBOARD";
export const PAGE_PROJECT_DETAILS = "PAGE_PROJECT_DETAILS";


